### ISSUE TITLE
HtoV-Toolbox

### ISSUE THREAD

**Issue by FarhadHakimov** [krischer/HtoV-Toolbox#2]
Could you help me with this error. Thank you. 
(obspy) farhad@farhad-K53E:~/Downloads/HtoV-Toolbox-master$ python htov_toolbox.py 
/home/farhad/anaconda3/envs/obspy/lib/python3.5/site-packages/obspy/core/util/deprecation_helpers.py:57: ObsPyDeprecationWarning: Function 'obspy.core.util.scoreatpercentile' is deprecated and will stop working with the next ObsPy version. Please use 'obspy.core.util.score_at_percentile' instead.
  warnings.warn(msg, ObsPyDeprecationWarning)
/home/farhad/anaconda3/envs/obspy/lib/python3.5/site-packages/obspy/core/util/deprecation_helpers.py:57: ObsPyDeprecationWarning: Function 'obspy.signal.trigger.zDetect' is deprecated and will stop working with the next ObsPy version. Please use 'obspy.signal.trigger.z_detect' instead.
  warnings.warn(msg, ObsPyDeprecationWarning)
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Traceback (most recent call last):
  File "htov_toolbox.py", line 1709, in <module>
    w = HtoV(main_window)
  File "htov_toolbox.py", line 47, in __init__
    self.setupUi(MainWindow)
  File "/home/farhad/Downloads/HtoV-Toolbox-master/htov_design.py", line 209, in setupUi
    self.lowpassSlider.setProperty("value", QtCore.QVariant(99))
TypeError: PyQt4.QtCore.QVariant represents a mapped type and cannot be instantiated

**Comment by megies** [comment]
Hi @FarhadHakimov, sorry for the delay.

I just tried it and it works for me on Linux 64bit using these instructions based on an Anaconda installation (at least I get the initial GUI screen, I did not do any actual calculations in the GUI):
https://github.com/krischer/HtoV-Toolbox#installation
